version: '3'
services:
    user-service:
      build:
        context: ./user-service
        dockerfile: Dockerfile
      ports:
        - "8000:8000"  # Map container port 9000 to host port 8000
      volumes:
        - ./user-service:/var/www/html
      networks:
        - app-network
      depends_on:
        - redis
      environment:
        - LOG_CHANNEL=custom
        - REDIS_PREFIX=demo
        - CACHE_DRIVER=redis
        - REDIS_CLIENT=predis
        - REDIS_HOST=redis
        - REDIS_PASSWORD=null
        - REDIS_PORT=6379
      command: php -S 0.0.0.0:8000 -t public
        
    notification-service:
      build:
        context: ./notification-service
        dockerfile: Dockerfile
      ports:
        - "9000:9000"  # Map container port 9000 to host port 8000
      volumes:
        - ./notification-service:/var/www/html
      networks:
        - app-network
      depends_on:
        - redis
      environment:
        - LOG_CHANNEL=custom
        - REDIS_PREFIX=demo
        - CACHE_DRIVER=redis
        - REDIS_CLIENT=predis
        - REDIS_HOST=redis
        - REDIS_PASSWORD=null
        - REDIS_PORT=6379
      command: php artisan notifier
    #   command: php -S 0.0.0.0:9000 -t public

    redis:
        image: redis:4.0
        container_name: app_redis
        ports:
            - "6382:6379"
        networks:
            - app-network

networks:
  app-network:
    driver: "bridge"